package org.github.caishijun.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-14T16:15:34.317+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://webservice.caishijun.github.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "say", targetNamespace = "http://webservice.caishijun.github.org/", className = "org.github.caishijun.webservice.Say")
    @ResponseWrapper(localName = "sayResponse", targetNamespace = "http://webservice.caishijun.github.org/", className = "org.github.caishijun.webservice.SayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String say(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
